// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Expression = 1,
  Operation = 2,
  Operator = 3,
  LeftParenthesis = 4,
  RightParenthesis = 5,
  String = 6;
