// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "!jOVQPOOO_QPO'#C^OOQO'#Cg'#CgQOQPOOOVQPO,58xOdQPO1G.dOVQPO'#CcOlQPO7+$OOOQO7+$O7+$OOOQO,58},58}OOQO-E6a-E6aOOQO<<Gj<<Gj",
  stateData: "t~OYOS~ORPOUQO~OSSO~OTWO[UO~OTZO[UO~O",
  goto: "q[PP]PPPPbPPPhVQOSUQVTRYVQROQTSRXU",
  nodeNames:
    "⚠ Expression Operation Operator LeftParenthesis RightParenthesis String",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData:
    "%{~R`X^!Tpq!Trs!xxy%ayz%f|}%k!c!}%p#R#S%p#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!YYY~X^!Tpq!T#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!{VOr!xrs#bs#O!x#O#P#g#P;'S!x;'S;=`$n<%lO!x~#gOU~~#jWOr!xrs$Ss#O!x#O#P#g#P;'S!x;'S;=`$t;=`<%l!x<%lO!x~$XVU~Or!xrs#bs#O!x#O#P#g#P;'S!x;'S;=`$n<%lO!x~$qP;=`<%l!x~$wWOr!xrs#bs#O!x#O#P#g#P;'S!x;'S;=`$n;=`<%l!x<%lO!x~%fOS~~%kOT~~%pO[~~%uQR~!c!}%p#R#S%p",
  tokenizers: [0],
  topRules: { Expression: [0, 1] },
  tokenPrec: 0,
});
