export const USERNAME_MIN_LENGTH = 5;
export const USERNAME_MAX_LENGTH = 30;
export const USERNAME_PATTERN = /^[a-zA-Z][a-zA-Z0-9]*$/;
export const PASSWORD_MIN_LENGTH = 12;
export const PASSWORD_MAX_LENGTH = 100;

export const CHARACTERS_MAX_COUNT = 20;
export const CHARACTER_NAME_MIN_LENGTH = 1;
export const CHARACTER_NAME_MAX_LENGTH = 40;
export const CHARACTER_MIN_ID = 1;
export const CHARACTER_MAX_ID = Number.MAX_SAFE_INTEGER;

export const ZONE_NAME_MIN_LENGTH = 1;
export const ZONE_NAME_MAX_LENGTH = 50;
export const ZONE_DESCRIPTION_MIN_LENGTH = 0;
export const ZONE_DESCRIPTION_MAX_LENGTH = 1000;
export const ZONE_MAX_WIDTH = 4;
export const ZONE_MAX_HEIGHT = 3;
export const ZONE_FIELD_NAME_MIN_LENGTH = 0;
export const ZONE_FIELD_NAME_MAX_LENGTH = 100;
export const ZONE_FIELD_DESCRIPTION_MIN_LENGTH = 0;
export const ZONE_FIELD_DESCRIPTION_MAX_LENGTH = 1000;
export const ZONE_EVENT_MAX_COUNT = 100;
export const ZONE_EVENT_NAME_MIN_LENGTH = 1;
export const ZONE_EVENT_NAME_MAX_LENGTH = 40;
export const ZONE_SEARCH_QUERY_MIN_LENGTH = 0;
export const ZONE_SEARCH_QUERY_MAX_LENGTH = ZONE_NAME_MAX_LENGTH;
export const ZONE_WHITELIST_MAX_COUNT = 1000;
export const ZONE_BLACKLIST_MAX_COUNT = 1000;
export const EXPRESSION_SOURCE_MAX_LENGTH = 1000;

export const VARIABLE_VALUE_MAX_LENGTH = 1000;
export const VARIABLE_MAX_COUNT = 1000;

export const SCENE_TEXT_MIN_LENGTH = 1;
export const SCENE_TEXT_MAX_LENGTH = 1000;
export const SCENE_TEXT_CHARACTER_NAME_MIN_LENGTH = 0;
export const SCENE_TEXT_CHARACTER_NAME_MAX_LENGTH = 100;
export const SCENE_LABEL_MIN_LENGTH = 1;
export const SCENE_LABEL_MAX_LENGTH = 100;
export const SCENE_VARIABLE_NAME_MIN_LENGTH = 1;
export const SCENE_VARIABLE_NAME_MAX_LENGTH = 100;
export const SCENE_CHOICE_OPTION_NAME_MIN_LENGTH = 1;
export const SCENE_CHOICE_OPTION_NAME_MAX_LENGTH = 100;
export const SCENE_CHOICE_OPTIONS_MAX_COUNT = 20;
export const SCENE_STEPS_MAX_COUNT = 1000;
export const SCENE_EXECUTED_STEPS_MAX_COUNT = 1000;

export const ITEM_NAME_MIN_LENGTH = 1;
export const ITEM_NAME_MAX_LENGTH = 100;
export const ITEM_DESCRIPTION_MIN_LENGTH = 0;
export const ITEM_DESCRIPTION_MAX_LENGTH = 1000;
export const ITEM_SEARCH_QUERY_MIN_LENGTH = 0;
export const ITEM_SEARCH_QUERY_MAX_LENGTH = ITEM_NAME_MAX_LENGTH;
export const ITEM_IN_INVENTORY_UNIQUE_MAX_COUNT = 1000;
export const ITEM_IN_INVENTORY_STACK_MAX_COUNT = 999999999;
export const ITEM_IMAGE_MAX_SIZE = 128 * 1024;
