export const USERNAME_MIN_LENGTH = 5;
export const USERNAME_MAX_LENGTH = 30;
export const USERNAME_PATTERN = /^[a-zA-Z][a-zA-Z0-9]*$/;
export const PASSWORD_MIN_LENGTH = 12;
export const PASSWORD_MAX_LENGTH = 100;

export const CHARACTERS_MAX_COUNT = 20;
export const CHARACTER_NAME_MIN_LENGTH = 1;
export const CHARACTER_NAME_MAX_LENGTH = 40;

export const ZONE_NAME_MIN_LENGTH = 1;
export const ZONE_NAME_MAX_LENGTH = 50;
export const ZONE_DESCRIPTION_MIN_LENGTH = 0;
export const ZONE_DESCRIPTION_MAX_LENGTH = 1000;
export const ZONE_MAX_WIDTH = 4;
export const ZONE_MAX_HEIGHT = 3;
export const ZONE_FIELD_NAME_MIN_LENGTH = 0;
export const ZONE_FIELD_NAME_MAX_LENGTH = 100;
export const ZONE_FIELD_DESCRIPTION_MIN_LENGTH = 0;
export const ZONE_FIELD_DESCRIPTION_MAX_LENGTH = 1000;
export const ZONE_EVENT_MAX_COUNT = 100;
export const ZONE_EVENT_NAME_MIN_LENGTH = 1;
export const ZONE_EVENT_NAME_MAX_LENGTH = 40;
export const ZONE_SEARCH_QUERY_MIN_LENGTH = 0;
export const ZONE_SEARCH_QUERY_MAX_LENGTH = ZONE_NAME_MAX_LENGTH;
