export enum ErrorCode {
  E_USERNAME_ALREADY_TAKEN = "E_USERNAME_ALREADY_TAKEN",
  E_INVALID_USERNAME_OF_PASSWORD = "E_INVALID_USERNAME_OF_PASSWORD",
  E_TOO_MANY_CHARACTERS = "E_TOO_MANY_CHARACTERS",
  E_CANNOT_ACQUIRE_LOCK = "E_CANNOT_ACQUIRE_LOCK",
  E_UNAUTHORIZED_ACCESS = "E_UNAUTHORIZED_ACCESS",
  E_INVALID_ZONE = "E_INVALID_ZONE",
  E_ZONE_NOT_FOUND = "E_ZONE_NOT_FOUND",
  E_ZONE_IS_DRAFT = "E_ZONE_IS_DRAFT",
  E_CHARACTER_NOT_FOUND = "E_CHARACTER_NOT_FOUND",
  E_NO_CHARACTER_ID = "E_NO_CHARACTER_ID",
  E_VALIDATION_ERROR = "E_VALIDATION_ERROR",
  E_CHARACTER_IN_ZONE = "E_CHARACTER_IN_ZONE",
  E_CHARACTER_NOT_IN_ZONE = "E_CHARACTER_NOT_IN_ZONE",
  E_ACCOUNT_NOT_FOUND = "E_ACCOUNT_NOT_FOUND",
  E_CANNOT_LEAVE = "E_CANNOT_LEAVE",
  E_CANNOT_MOVE = "E_CANNOT_MOVE",
  E_NO_ACCESS_TO_ZONE = "E_NO_ACCESS_TO_ZONE",
  E_SCENE_ENDED = "E_SCENE_ENDED",
  E_SCENE_CHOICE_REQUIRED = "E_SCENE_CHOICE_REQUIRED",
  E_SCENE_INVALID_CHOICE = "E_SCENE_INVALID_CHOICE",
  E_EVENT_NOT_FOUND = "E_EVENT_NOT_FOUND",
  E_CANNOT_INTERACT_WITH_EVENT = "E_CANNOT_INTERACT_WITH_EVENT",
  E_CHARACTER_IN_SCENE = "E_CHARACTER_IN_SCENE",
}

export interface ErrorResponse {
  code: ErrorCode;
  message: string;
}
