export enum ErrorCode {
  E_USERNAME_ALREADY_TAKEN = "E_USERNAME_ALREADY_TAKEN",
  E_INVALID_USERNAME_OF_PASSWORD = "E_INVALID_USERNAME_OF_PASSWORD",
  E_TOO_MANY_CHARACTERS = "E_TOO_MANY_CHARACTERS",
  E_CANNOT_ACQUIRE_LOCK = "E_CANNOT_ACQUIRE_LOCK",
  E_UNAUTHORIZED_ACCESS = "E_UNAUTHORIZED_ACCESS",
  E_INVALID_ZONE = "E_INVALID_ZONE",
  E_ZONE_NOT_FOUND = "E_ZONE_NOT_FOUND",
  E_CHARACTER_NOT_FOUND = "E_CHARACTER_NOT_FOUND",
  E_NO_CHARACTER_ID = "E_NO_CHARACTER_ID",
  E_VALIDATION_ERROR = "E_VALIDATION_ERROR",
  E_CHARACTER_IN_ZONE = "E_CHARACTER_IN_ZONE",
  E_CHARACTER_NOT_IN_ZONE = "E_CHARACTER_NOT_IN_ZONE",
  E_ACCOUNT_NOT_FOUND = "E_ACCOUNT_NOT_FOUND",
  E_CANNOT_LEAVE = "E_CANNOT_LEAVE",
  E_CANNOT_MOVE = "E_CANNOT_MOVE",
  E_NO_ACCESS_TO_ZONE = "E_NO_ACCESS_TO_ZONE",
  E_SCENE_CHOICE_REQUIRED = "E_SCENE_CHOICE_REQUIRED",
  E_SCENE_INVALID_CHOICE = "E_SCENE_INVALID_CHOICE",
  E_EVENT_NOT_FOUND = "E_EVENT_NOT_FOUND",
  E_CANNOT_INTERACT_WITH_EVENT = "E_CANNOT_INTERACT_WITH_EVENT",
  E_CHARACTER_IN_SCENE = "E_CHARACTER_IN_SCENE",
  E_CHARACTER_NOT_IN_SCENE = "E_CHARACTER_NOT_IN_SCENE",
  E_ITEM_NOT_FOUND = "E_ITEM_NOT_FOUND",
  E_NO_ACCESS_TO_ITEM = "E_NO_ACCESS_TO_ITEM",
  E_INVALID_ITEM = "E_INVALID_ITEM",
  E_CANNOT_WEAR_ITEM = "E_CANNOT_WEAR_ITEM",
  E_IMAGE_NOT_FOUND = "E_IMAGE_NOT_FOUND",
  E_IMAGE_MAX_COUNT_EXCEEDED = "E_IMAGE_MAX_COUNT_EXCEEDED",
  E_IMAGE_MAX_TOTAL_SIZE_EXCEEDED = "E_IMAGE_MAX_TOTAL_SIZE_EXCEEDED",
}

export interface ErrorResponse {
  code: ErrorCode;
  message: string;
}
