name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        working-directory: .
        run: pnpm install --frozen-lockfile
      - name: bondage-fantasy-client - check format
        working-directory: ./bondage-fantasy-client
        run: pnpm run format-check
      - name: bondage-fantasy-client - lint
        working-directory: ./bondage-fantasy-client
        run: pnpm run lint
      - name: bondage-fantasy-client - build
        working-directory: ./bondage-fantasy-client
        run: pnpm run build
      - name: bondage-fantasy-server - check format
        working-directory: ./bondage-fantasy-server
        run: pnpm run format-check
      - name: bondage-fantasy-server - lint
        working-directory: ./bondage-fantasy-server
        run: pnpm run lint
      - name: bondage-fantasy-server - build
        working-directory: ./bondage-fantasy-server
        run: pnpm run build
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push bondage-fantasy-client Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./bondage-fantasy-client
          file: ./bondage-fantasy-client/Dockerfile
          push: true
          tags: ghcr.io/xenonrope/bondage-fantasy-client
      - name: Build and push bondage-fantasy-server Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./bondage-fantasy-server
          file: ./bondage-fantasy-server/Dockerfile
          push: true
          tags: ghcr.io/xenonrope/bondage-fantasy-server
